### ISSUE TITLE
Memento aggregator

### ISSUE THREAD

**Issue by markosii** [webrecorder/pywb#310]
Hi, 
I tested this memento aggregator sample :

[http://pywb.readthedocs.io/en/latest/manual/warcserver.html#sample-memento-aggregator](http://pywb.readthedocs.io/en/latest/manual/warcserver.html#sample-memento-aggregator)

I have this in my config.yaml :
```
collections:
    iam: memento+https://web.archive.org/web/
    many_archives:
        index_group:
            rhiz: memento+http://webenact.rhizome.org/all/
            iam: memento+https://web.archive.org/web/
            iac: cdx+http://web.archive.org/cdx;/web
            apt: memento+http://arquivo.pt/wayback/
```
when i ask for [http://localhost:8080/many_archives/](http://localhost:8080/many_archives/) I have this :

![1](https://user-images.githubusercontent.com/36041989/37025927-421468d6-212d-11e8-8ee4-d317590c7adc.PNG)

and then this :

![2png](https://user-images.githubusercontent.com/36041989/37025931-43fd6a1c-212d-11e8-9891-2d9f7abedf08.PNG)

`0 capture`, witch isn't true beacause when I ask for [http://localhost:8080/iam/](http://localhost:8080/iam/), it works and I have this :

![3png](https://user-images.githubusercontent.com/36041989/37025937-46f2c000-212d-11e8-97a5-50b3f7761e13.PNG)

The problem is that `many_archives` does not work for me, can you help me fix this issue?

Thanks
