### ISSUE TITLE
Encoding issues with many popular sites

### ISSUE THREAD

**Issue by pirate** [webrecorder/pywb#434]
## Describe the bug
When using `wayback` in both `--proxy` and `--proxy-record` mode, many sites seem to display gibberish, possibly because of an incorrect encoding being forced somewhere.

Working sites:
 - https://example.com
 - https://reddit.com
 - https://github.com
 - and many more...

Broken sites:
 - https://google.com
 - https://facebook.com
 - https://www.cloudflare.com
 - and many more...

I'm not sure what makes some sites work and not others.

## Steps to reproduce the bug
1. Use Python 3.7.2 and either pywb v2.1.0 or pywb-2.2.0.dev0 (latest `develop` branch)
2. Using an empty `config.yaml`, run:
```bash
wb-manager init demo
wayback --proxy-record --proxy demo
```
3. Open a page in a browser:
```bash
google-chrome --proxy-server=http://localhost:8080 --ignore-certificate-errors --disable-web-security https://cloudflare.com
```

## Expected behavior
A readable site is recorded and replayed instead of ��������

## Screenshots
![image](https://user-images.githubusercontent.com/511499/51600020-03a94800-1ecf-11e9-98bd-af26531c360b.png)

## Environment
- OS: macOS 10.14
- Browser: Google Chrome 72.0.3626.64 beta
- Version: Python 3.7.2 and pywb v2.1.0 [e.g. 22]

**Comment by N0taN3rd** [comment]
Have you tried using a non-empty config file and ensured that pywb auto-generated a CA ([docs](https://pywb.readthedocs.io/en/latest/manual/configuring.html#https-proxy-and-pywb-certificate-authority)) and or the dev branch?

I was not able to reproduce the issue using the config below when running from the dev branch using 3.7.2 and linux.
 
```yml
collections:
    all: $all
    live: $live

# Settings for each collection
use_js_obj_proxy: true

# Memento support, enable
enable_memento: true

# Replay content in an iframe
framed_replay: true
```
