### ISSUE TITLE
Support specifying a custom endpont_url for S3

### ISSUE THREAD

**Issue by ikreymer** [webrecorder/pywb#579]
## Is your feature request related to a problem? Please describe.

boto3 allows custom endpoint_urls, but they can not be set via an environment variable.

This would allow using `s3://` paths with other AWS-compatible S3 deployments.

## Describe the solution you'd like
Provide a way to set the boto3 client `endpoint_url` from either an env var or a config.yaml option.

**Comment by white-gecko** [comment]
This can be done by providing `AWS_ENDPOINT_URL_S3` resp. all of `AWS_ENDPOINT_URL_S3`, `AWS_DEFAULT_REGION`, `AWS_ACCESS_KEY_ID`, and `AWS_SECRET_ACCESS_KEY` as environment variables. An example configuration would look like:

```yaml
collections:
  warcs:
    archive_paths: "s3://webarchive/"
    index_paths: cdx+http://outbackcdx-service:8080/outbackcdx/warcs
```

`webarchive` is the bucket name.
